name: Update Live IPTV

on:
  push:
    branches: [main]
    paths:
      - 'auto_update/**'
  workflow_dispatch:
  schedule:
    - cron: '01,30 * * * *'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run update script
        run: bash ./auto_update/update_liveURL.sh

      - name: Check for changes
        id: files_changed
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Changes detected"
            echo "is_changed=1" >> $GITHUB_ENV
          else
            echo "No changes detected"
            echo "is_changed=0" >> $GITHUB_ENV
          fi

      - name: Commit and Push changes
        if: env.is_changed == '1'
        run: |
          git config --local user.email "120372062+KoolCenter@users.noreply.github.com"
          git config --local user.name "KoolCenter"
          git add .
          git commit -m "Actions Auto Update at $(date +'%Y-%m-%d %H:%M:%S')"
          git push
          
      - name: Delete old workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          keep_minimum_runs: 10
