name: Update Live IPTV

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/update_LiveURL.yml'
      - 'LiveURL*'
  workflow_dispatch:
    inputs:
      FORCE_PUSH:
        description: 'Force to push'
        required: true
        default: 'false'
  schedule:
    - cron: '45 19 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Run update script
        run: |
          cd "${GITHUB_WORKSPACE}/auto_update"
          bash update_liveURL.sh

      - name: Commit to repo
        if: env.is_changed == '1' || github.event.inputs.FORCE_PUSH == 'true'
        run: |
          cd $GITHUB_WORKSPACE
          git config --local user.email "120372062+KoolCenter@users.noreply.github.com"
          git config --local user.name "KoolCenter"
          git add LiveURL/.
          git commit -m "Actions Auto Update at $(date +'%Y-%m-%d %H:%M:%S')"
          git push

      - name: Delete old workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          keep_minimum_runs: 30
